package service;

public enum ServiceTypes {
    COMPLAIN_SERVICE,
    EMPLOYEE_SERVICE,
    GUEST_SERVICE,
    HALL_SERVICE,
    HALL_RESERVATION_SERVICE,
    MAINTENACE_SERVICE,
    MEAL_ORDERS_SERVICE,
    MEAL_PACKAGE_SERVICE,
    PAYMENT_SERVICE,
    ROOM_SERVICE,
    ROOM_RESERVATION_SERVICE,
    USERS_SERVICE
}
